name: Release

on:
  workflow_dispatch:
    inputs:
      dry-run:
        required: true
        description: 'Run dry run?'
        type: boolean
        default: true

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Set dry run env variable
        run: |
          if [ "${{ github.event.inputs.dry-run }}" == "true"  ]; then
            echo "PUBLISH=--dry-run" >> $GITHUB_ENV
          fi
      - name: Install
        run: yarn
      - run: yarn install --immutable --immutable-cache --check-cache
      - run: yarn build
      - run: npx semantic-release $(echo "${{ env.PUBLISH }}")
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}